import PDFDocument from "pdfkit";
import Visitor from "../model/visitormodel.js";

export const exportUsersService = async () => {

  const users = await Visitor.find();

  const doc = new PDFDocument({
    size: "A4",
    margin: 40,
  });

  const buffers = [];

  doc.on("data", (chunk) => {
    buffers.push(chunk);
  });

  // ===================================================
  // HEADER
  // ===================================================

  doc
    .rect(0, 0, 595, 80)
    .fill("#0F172A");

  doc
    .fillColor("white")
    .fontSize(24)
    .text(
      "Visitor Management System",
      40,
      25
    );

  doc
    .fontSize(12)
    .text(
      "Visitors Export Report",
      40,
      55
    );

  doc.moveDown(4);

  // ===================================================
  // REPORT INFO
  // ===================================================

  doc
    .fillColor("#111827")
    .fontSize(11)
    .text(
      `Generated At: ${new Date().toLocaleString()}`,
      40,
      100
    );

  doc.moveDown(2);

  // ===================================================
  // USERS CARDS
  // ===================================================

  users.forEach((user, index) => {

    // ===================================================
    // PAGE BREAK
    // ===================================================

    if (doc.y > 650) {
      doc.addPage();
    }

    const startY = doc.y;

    // ===================================================
    // TITLE
    // ===================================================

    doc
      .fillColor("#2563EB")
      .fontSize(18)
      .text(
        `Visitor #${index + 1}`,
        50,
        startY + 10
      );

    doc.moveDown(1.5);

    // ===================================================
    // BASIC DETAILS
    // ===================================================

    doc
      .fillColor("#111827")
      .fontSize(14)
      .text("Basic Details");

    doc
      .fillColor("black")
      .fontSize(12)
      .text(
        `Name: ${user.name || "N/A"}`
      )
      .text(
        `Email: ${user.email || "N/A"}`
      )
      .text(
        `Phone: ${user.phone || "N/A"}`
      );

    doc.moveDown();

    // ===================================================
    // ID DETAILS
    // ===================================================

    doc
      .fillColor("#111827")
      .fontSize(14)
      .text("Identity Details");

    doc
      .fillColor("black")
      .fontSize(12)
      .text(
        `ID Type: ${user.idType || "N/A"}`
      )
      .text(
        `ID Number: ${user.idNumber || "N/A"}`
      );

    doc.moveDown();

    // ===================================================
    // ACCOUNT DETAILS
    // ===================================================

    doc
      .fillColor("#111827")
      .fontSize(14)
      .text("Account Details");

    doc
      .fillColor("black")
      .fontSize(12)
      .text(
        `Created By: ${user.createdBy || "N/A"}`
      )
      .text(
        `Verified: ${
          user.verified
            ? "YES"
            : "NO"
        }`
      )
      .text(
        `Created At: ${new Date(
          user.createdAt
        ).toLocaleString()}`
      );

    if (user.expiresAt) {

      doc.text(
        `Expires At: ${new Date(
          user.expiresAt
        ).toLocaleString()}`
      );
    }

    doc.moveDown();

    // ===================================================
    // STATUS
    // ===================================================

    let statusColor = "red";

    if (user.verified) {
      statusColor = "green";
    }

    doc
      .fillColor(statusColor)
      .fontSize(13)
      .text(
        `Verification Status: ${
          user.verified
            ? "VERIFIED"
            : "NOT VERIFIED"
        }`
      );

    doc.moveDown(1.5);

    // ===================================================
    // BORDER
    // ===================================================

    const endY = doc.y;

    doc
      .roundedRect(
        35,
        startY,
        525,
        endY - startY + 10,
        10
      )
      .stroke("#CBD5E1");

    doc.moveDown(2);
  });

  // ===================================================
  // FOOTER
  // ===================================================

  doc
    .fontSize(10)
    .fillColor("gray")
    .text(
      "Generated by Visitor Management System",
      170,
      760,
      {
        align: "center",
      }
    );

  doc.end();

  return await new Promise((resolve) => {

    doc.on("end", () => {

      resolve(
        Buffer.concat(buffers)
      );

    });

  });

};